version: '3.7'

services:
  the-welfplatform-club:
    container_name: the-welfplatform-club
    restart: always
    build: .
    environment:
      PORT: 80
      PUBLIC_URL: https://the.welfplatform.club
      VIRTUAL_HOST: the.welfplatform.club
      LETSENCRYPT_HOST: the.welfplatform.club
      LETSENCRYPT_EMAIL: hello@jackallen.me
    expose:
      - 80
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
